### PR TITLE
Update wgpu with bundle support

### PR DESCRIPTION
**Pull request by kvark**
Depends on https://github.com/gfx-rs/wgpu/pull/286
Blocked on https://github.com/eqrion/cbindgen/issues/532 :(

### CODE REVIEW

**Comment by cwfitzgerald** [comment]
Now that #34 finally got in, this should be able to cleanly rebase on top of that and be good to go. I want to get this in before I do any of the refactoring for #41 or #42, so this pr doesn't have any substantial conflicts.

**Comment by kvark** [comment]
@cwfitzgerald I updated this and rebased. Unfortunately, hitting https://github.com/eqrion/cbindgen/issues/532
Perhaps, some of the `FastHashMap` got through and gets processed by cbindgen? If we know what this is, we could add it to the exclude list.

**Comment by cwfitzgerald** [comment]
Hum. I'll take a look later to try figure out what's going on.

**Comment by kvark** [comment]
Alright, this is ready now. Just waiting on cbindgen-0.14.4 to be released. cc @emilio

**Comment by kvark** [comment]
Hmm, I guess we can proceed with merging this, as CI is happy.
Expecting cbindgen to be released soon...
bors r+

**Comment by kvark** [comment]
bors retry

**Pull request merged**
