### PR TITLE
Feature/enumerate adapters

### PR DESCRIPTION
**Pull request by toloudis**
I would love some advice on how to proceed with this.

I am interested in potentially using wgpu-native as a cross-platform graphics api.  For my application, a volume rendering tool for scientific data (https://www.allencell.org/pathtrace-rendering.html), it makes sense to be able to support multi-gpu systems and potentially allow gpu selection by very custom means.  

So I have done a very basic first pass at exposing enumerate_adapters but the enumeration I get spans all possible backends.  Apart from checking against a previously created "compatible surface", is there some way to detect a current backend at run time?  Or is it reasonable to return adapters from all supported back ends?

Also api advice welcomed: for example, should there be a callback passed in to wgpuInstanceEnumerateAdapters?

### CODE REVIEW

**Comment by cwfitzgerald** [comment]
Sorry for the very long delay

> is there some way to detect a current backend at run time? 

Depends on what you mean by current. All supported backends are active on the instance at all times. Enumerate adapters can be further limited by the backend list.

I'll leave the C interface advice to @rajveermalviya

**Comment by kushalkolar** [comment]
Wondering if this PR can receive any traction in the near future? It would be useful to select a specific GPU as the adapter in multi-GPUs systems. These can either be shared systems where multiple users login to a single multi-GPU system, and should ideally be able to choose a GPU based on what's available. Or on multi-GPU systems where some GPUs are being used for compute (CUDA, training neural networks, etc.), and other GPUs are used for visualization.

Similar to the author of this PR, we are also using it for scientific visualization via `wgpu-py`: https://github.com/kushalkolar/fastplotlib/

**Comment by rajveermalviya** [comment]
Apologies for the long delay, somehow I missed this PR.

In order to get this merged ASAP, I have rebased and made some changes fixing the possible memory leak.
Also added an mini example demonstrating the use.

As for the C API, double call seems fine as this will probably be called only once in an application.

**Comment by kushalkolar** [comment]
Wow, you guys are epic :smile: !

**Review by almarklein — APPROVED** [review]

**Comment by toloudis** [comment]
Thank you!

**Pull request merged**
