### PR TITLE
support for emscripten build

### PR DESCRIPTION
**Pull request by caiiiycuk**
Added support for emscripten build. It's draft because, I am waiting for completion of other PRs (wgpu, headers).
Also, how I can edit wiki to add emscripten instructions?

--
изображение

### CODE REVIEW

**Comment by caiiiycuk** [comment]
Blocked by: 
* #168 
* https://github.com/webgpu-native/webgpu-headers/pull/146
* https://github.com/gfx-rs/wgpu/pull/2450/files
* +wiki

**Comment by caiiiycuk** [comment]
@kvark can we fork webgpu-headers under gfx-rs to apply emscripten workaound? https://github.com/webgpu-native/webgpu-headers/pull/146

**Comment by kvark** [comment]
We can, yeah, although it would be good to not do that:)
Didn't you also try to make our ID to be 32bit on those systems?

**Comment by caiiiycuk** [comment]
> We can, yeah, although it would be good to not do that:) Didn't you also try to make our ID to be 32bit on those systems?

Yes I tried, and this solution also works. But, I really worried that 65536 is too small for index/epoch? Or you think its ok?


--

Another solution that I have in mind is to doing copy of headers and patch them when make:
```sh
make lib-native-emscripten
```

It will cp webgpu.h into emscripten/webgpu.h  and patch it. What do you think is it acceptable?

**Comment by kvark** [comment]
I think 32-bit indices are acceptable, especially with https://github.com/gfx-rs/wgpu/pull/2462 merged.
It's certainly not ideal, but it should work.

**Comment by caiiiycuk** [comment]
ready

**Review by kvark — CHANGES_REQUESTED** [review]

**Comment by rajveermalviya** [comment]
Closing this as on web/wasm Emscripten provides it's own `webgpu.h` implementation which binds to the WebGPU JS functions directly. It doesn't make sense for `wgpu-native` to "support" emscripten if user wants to target browser webgpu.

Only thing `wgpu-native` can provide in emscripten/wasm context is an implementation of `webgpu.h` with WebGL2 backend. If that's what users want, then please open a new issue stating your usecase.

**Pull request closed without merging**
