### PR TITLE
Update to latest wgpu-core

### PR DESCRIPTION
**Pull request by almarklein**
I get the following error when I try to run any example:
```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`: ShaderModule[0] is no longer alive', /Users/almar/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/988990c/wgpu-core/src/hub.rs:169:9
```

Does anyone have an idea why this is?

### CODE REVIEW

**Comment by almarklein** [comment]
@almarklein Thanks, that seems to be a needed change indeed, but it does not fix the error. I get the same error if I add gibberish in the shader, so it looks like it never gets to parsing/compiling it.

**Comment by almarklein** [comment]
Correction, I do get some examples to run by changing both the `[[xxx]]` decorators, and also using `,`instead of `;` in struct separators.

So, I guess we have a new bug, where syntax errors in the wgsl result in a seemingly unrelated error.

**Comment by rajveermalviya** [comment]
> So, I guess we have a new bug, where syntax errors in the wgsl result in a seemingly unrelated error.

it does report those errors via `UncapturedErrorCallback`.

**Comment by almarklein** [comment]
> it does report those errors via UncapturedErrorCallback.

Aha! Thanks, I did see that come by some time ago. Time to implement that in wgpu-py.

**Comment by almarklein** [comment]
After making the necessary updates in wgpu-py, it's test suite passes with this new version. Even fixes some tests that failed specifically on MacOS.

**Pull request merged**
