### PR TITLE
Show memory report in debug builds

### PR DESCRIPTION
**Pull request by sqaxomonophonen**
`log::debug!()` after `wgpuSwapChainPresent()` which is assumed to be called roughly once per frame. This is useful for detecting memory leaks.

See also: #186

### CODE REVIEW

**Comment by kvark** [comment]
I suggested doing it in debug only, and now I'm having second thoughts. Sorry about this!
This memory dump can be quite verbose if done every frame.
Perhaps, we should just expose it as a C function and let the users call it when needed?

**Comment by sqaxomonophonen** [comment]
It could be argued that the WebGPU specification *itself* is lacking a way to get a resource usage report (for the same reason it has `.destroy()` methods; it implies the possibility of resource management problems even in pure JS+WebGPU applications). So any solution we come with is likely going to be temporary? I'm also fine with adding something like this to `wgpu.h`:
```c
void wgpuLogResourceUsage(); // calls your WGPULogCallback with WGPULogLevel=0 regardless of log level
// *OR*:
char* wgpuGetResourceUsageString(); // caller "owns" the returned C-string and must free() it
```
Compared to the implicit logging after `wgpuSwapChainPresent()` it has a higher risk of breaking forward compatibility, but it's easy to fix (compared with all the other forward compatibility issues). It doesn't add unavoidable verbosity, and it also works better with multi-window programs, or programs that don't want a report every frame.

Anything more complicated than this (like getting the report in a C struct), and I think the effort will we wasted here and better spent discussing it with the WebGPU people. Thankfully, running a custom build of `wgpu-native` is easy (:+1:), and I'm fine with it for the time being, so feel free to `.destroy()` this PR if neither solution sits well with you :smiley:

**Comment by kvark** [comment]
`wgpuGetResourceUsageString` sounds good to land here

**Comment by sqaxomonophonen** [comment]
Does this look good?

I tested with the `triangle` example, and this works as expected:
```diff
diff --git a/examples/triangle/main.c b/examples/triangle/main.c
index 0de6675..4c2a8b0 100644
--- a/examples/triangle/main.c
+++ b/examples/triangle/main.c
@@ -342,6 +342,10 @@ int main() {
     wgpuSwapChainPresent(swapChain);
 
     glfwPollEvents();
+
+    char* usage = wgpuGetResourceUsageString();
+    printf("ru: %s\n", usage);
+    free(usage);
   }
 
   glfwDestroyWindow(window);
```

**Review by kvark — APPROVED** [review]

**Pull request merged**
