### PR TITLE
update to latest wgpu-core

### PR DESCRIPTION
**Pull request by radgeRayden**
Fixes version conflicts, updates the naga url to point to the main wgpu repo, some changes that arise from the bump to raw-window-handle 0.6.0. I am a Rust noob so please let me know if anything is amiss or bad style.

### CODE REVIEW

**Comment by radgeRayden** [comment]
I realize now that I wasn't seeing checks for non-Linux code paths which introduced some errors I didn't catch. Will fix it all tomorrow.

**Review by rajveermalviya — APPROVED** [review]

**Review by almarklein — APPROVED** [review]

**Comment by rajveermalviya** [comment]
(Sorry for the late merge, somehow this got left out.)

After this is merged wgpu-native's trunk will target wgpu trunk, so any future changes would not be released until next major wgpu release, though we could backport some of them if possible to the v0.18 branch and make a dot release.

**Comment by almarklein** [comment]
wgpu-core 0.18.1 released yesterday, should we update to that in a new pr? Perhaps  create a v0.18 branch?

**Review by almarklein — APPROVED** [review]

**Comment by rajveermalviya** [comment]
> wgpu-core 0.18.1 released yesterday, should we update to that in a new pr? 

Created https://github.com/gfx-rs/wgpu-native/pull/319, let's merge that one first then this one.

**Comment by rajveermalviya** [comment]
Merging! Thanks!

**Pull request merged**
