### PR TITLE
Remove cfg_aliases and apply cfgs inline

### PR DESCRIPTION
**Pull request by rajveermalviya**
Addresses https://github.com/gfx-rs/wgpu-native/pull/351#issuecomment-2311486542

### CODE REVIEW

**Review by almarklein — APPROVED** [review]

**Comment by hmaarrfk** [comment]
Thanks for addressing this quickly. I am going to try to give this a go in case it fixes things. 

Is there any chance of a new release for me to avoid « back porting » the patch?

**Comment by hmaarrfk** [comment]
I think our issues at conda-forge are likely more widespread. So it may be unrelated to this

**Comment by almarklein** [comment]
> Is there any chance of a new release for me to avoid « back porting » the patch?

A new release was just published.

**Comment by hmaarrfk** [comment]
Thank you for the release. whatever happened it seems like osx-arm build is fixed.

**Comment by hmaarrfk** [comment]
Definitely the .2 release helped.

It might have been some of the dependencies that you updated here.

So in either case, thank you again!
xref: https://github.com/conda-forge/wgpu-native-feedstock/pull/23 (tried to revert to the .1 and you see the failure again)

**Pull request merged**
