### PR TITLE
Updated to newer version of wgpu: rev 847d9748f525b3725564e933b83f11cc5a7abb83

### PR DESCRIPTION
**Pull request by porky11**
In order to build ffi/wgpu.h now, you need a more recent version of cbindgen, at least d652d29ae28f9b83bead8feca98cdd30752e63fa (see https://github.com/eqrion/cbindgen/issues/532).

### CODE REVIEW

**Comment by kvark** [comment]
Needs a rebase now!

**Comment by almarklein** [comment]
Would it make sense to do another release once this is merged?

**Comment by kvark** [comment]
@almarklein sure! we are still very much behind wgpu-core, so more things will follow

**Comment by kvark** [comment]
I believe this is superseded by #47

**Pull request closed without merging**
