### PR TITLE
Attemp to build for macos m1

### LINKED ISSUE #138: Build binaries for Mac M1 architecture
I suppose this would be a matter of adding a CD build that runs MacOS and cross-compiles for M1 - does that work?

### PR DESCRIPTION
**Pull request by almarklein**
Closes #138. Needs testing by ppl with an actual M1.

I copied most of the recipe from https://github.com/rust-analyzer/rust-analyzer/blob/master/.github/workflows/release.yaml

### CODE REVIEW

**Comment by Korijn** [comment]
Any instructions for testing?

**Comment by kvark** [comment]
I suppose the question here is - would the produced library be working on M1?
In order to test it, @almarklein could build it locally and upload the library somewhere for @Korijn to try running some wgpu-native stuff with.

**Comment by SuperSimon81** [comment]
I just built the binaries on a M1 mac. Triangle works and runs natively, ie. not through rosetta 2.

**Comment by almarklein** [comment]
The CD for this branch runs on my fork. I will put instructions here to test the CD-generated binaries.

**Comment by almarklein** [comment]
Ok, this seems to work. To test this:

* Download and extract thiszipfile: https://github.com/almarklein/wgpu-native/releases/download/v0.9.2.2/wgpu_binaries_test_01.zip
* Run the Python script that's in there

The script tries to load the lib in Python and call the `getVersion` function. For me (on Windows) this produces:
```
libwgpu_native_macos_64_release.dylib failed
libwgpu_native_macos_arm64_debug.dylib failed
libwgpu_native_macos_arm64_release.dylib failed
test_binaries.py failed
wgpu_native_win_64_release.dll (0, 0, 0, 0)
```

Running via Rosetta should work for the `macos_64_release` build, and without Rosetta the arm64 builds should work. The version that is displayed is all zeros, nevermind that.

**Comment by SuperSimon81** [comment]
Running it as is produces: 

```
libwgpu_native_macos_64_release.dylib failed
test_binaries.py failed
libwgpu_native_macos_arm64_debug.dylib failed
libwgpu_native_macos_arm64_release.dylib failed
wgpu_native_win_64_release.dll failed
```
printing err inside your script gives:

```
Did find:
        /Users/simon/Documents/coding/wgpu/test/libwgpu_native_macos_arm64_release.dylib: mach-o, but wrong architecture
```

However, putting the binary I compiled in the directory and running test_binaries.py gives:

```
libwgpu_native-mybuild-release.dylib (0, 0, 0, 0)
...

```

**Comment by almarklein** [comment]
@SuperSimon81 What if you run the script with Rosetta (Python x86)?

**Comment by SuperSimon81** [comment]
Using rosetta:

```
libwgpu_native_macos_64_release.dylib (0, 0, 0, 0)
libwgpu_native_macos_arm64_debug.dylib (0, 0, 0, 0)
libwgpu_native_macos_arm64_release.dylib (0, 0, 0, 0)
```

The others fail. I guess you are right about them being the x86 libs.

**Comment by almarklein** [comment]
Ok, I decided to refactor the CD module so each build is self-contained, making it easier to read/maintain. Took me longer to get everything running correctly again, but from hereout it should be easier to add builds for other targets.

Could you have another try with: https://github.com/almarklein/wgpu-native/releases/download/v0.9.2.12/wgpu_binaries_test05.zip

**Comment by SuperSimon81** [comment]
I am happy to report that:
```
---- libwgpu-macos-arm64-debug.dylib
OK (0, 9, 2, 11)
---- libwgpu-macos-arm64-release.dylib
OK (0, 9, 2, 11)
```

The others fail obviously.

Well done!

**Pull request merged**
