### PR TITLE
Fix the compute example

### PR DESCRIPTION
**Pull request by lancelet**
- Update `shader.wgsl` from wgpu: https://github.com/gfx-rs/wgpu/blob/master/wgpu/examples/hello-compute/shader.wgsl

### CODE REVIEW

**Review by almarklein — APPROVED** [review]

**Review by kvark — APPROVED** [review]

**Comment by kvark** [comment]
@almarklein we should be detecting this on CI...

**Comment by almarklein** [comment]
Yeah, but that'd mean running the examples on CI, which we cannot do yet, can we?

**Comment by kvark** [comment]
We can! We can do a lot of things.
At the very minimum, we can just run Naga in the build step and parse the source code.
We can actually run the native example on Windows CI, which exposes software implementation (WARP) on DX12.
wgpu has been running GPU tests on Windows CI for a while

**Comment by almarklein** [comment]
#131

**Pull request merged**
