### PR TITLE
Implement GLSL shader source

### LINKED ISSUE #195: Add GLSL ShaderSource support
Naga and WGPU support GLSL as shader sources and while WebGPU doesn't support it, it could still be beneficial to some people, maybe behine a native feature. How could I go about adding support for it? That is if it is something that would be accepted.

### PR DESCRIPTION
**Pull request by MineGame159**
Implemented GLSL shader source with support for passing in pre-processor defines.
From my testing it works perfectly.
Closes #195.

### CODE REVIEW

**Comment by MineGame159** [comment]
Well this is weird, the Windows builds fail because it expects `i32` instead of `u32` but when I try to do `as i32` it complains that it expects `u32` and not `i32`. Would appreciate some help here.

Also I don't know what is going on with the integrity checks, they aren't failing because of any function I modified.

**Comment by rajveermalviya** [comment]
this should be added in [webgpu-headers](https://github.com/webgpu-native/webgpu-headers) too

> Also I don't know what is going on with the integrity checks

it's because it didn't account for `nullable` annotations, should be fixed by #196

**Comment by MineGame159** [comment]
Oh I thought [webgpu-headers](https://github.com/webgpu-native/webgpu-headers) are supposed to be kept in sync with the official webgpu spec. I could make PR there too.

**Comment by rajveermalviya** [comment]
nvm, looked into [tint](https://dawn.googlesource.com/tint/) (dawn's naga) it doesn't support GLSL reader (yet?).
so, seems pretty unlikely, it will be added.

**Comment by MineGame159** [comment]
Well in my opinion it could still be merged just here just like other native features that are not part of the webgpu spec but I am not the one making that decision.

**Comment by rajveermalviya** [comment]
Yep here is definitely fine, wgpu-native should export everything that wgpu does :)

Just that IMO common features between dawn & wgpu should be exported in webgpu-headers.

**Review by cwfitzgerald — APPROVED** [review]
LGTM, just have CI issues

**Comment by MineGame159** [comment]
Well I have no idea why it fails for Windows builds (explained more in my second comment) and would appreciate some help.

**Comment by almarklein** [comment]
> Also I don't know what is going on with the integrity checks, they aren't failing because of any function I modified.

This is because of the new webgpu-headers, and will be fixed as part of #196.

**Comment by almarklein** [comment]
> Well I have no idea why it fails for Windows builds (explained more in my second comment) and would appreciate some help.

My knowledge of Rust is limited. What I found so far:

CI complaints:
```
error[E0308]: mismatched types
   --> src\conv.rs:403:77
    |
403 |         let mut options = naga::front::glsl::Options::from(map_shader_stage(glsl.stage).expect("Unknown shader stage"));
    |                                                                             ^^^^^^^^^^ expected `i32`, found `u32`
    |
help: you can convert a `u32` to an `i32` and panic if the converted value doesn't fit
    |
403 |         let mut options = naga::front::glsl::Options::from(map_shader_stage(glsl.stage.try_into().unwrap()).expect("Unknown shader stage"));
    |                                                                                       ++++++++++++++++++++

```

Definition of `map_shader_stage` (added in this PR):
```rust
map_enum!(
    map_shader_stage,
    WGPUShaderStage,
    naga::ShaderStage,
    Vertex,
    Fragment,
    Compute
);
```

Why does the compiler think that `map_shader_stage` need an i32 - it's an enum?

**Comment by MineGame159** [comment]
No idead, if you expand the macro the function just takes in `native::WGPUShaderStage` which should be exactly the same type as what I pass in.

**Comment by MineGame159** [comment]
Well now it fails on nightly MacOS for a change but I don't think that is caused by my changes. 😅

**Comment by rajveermalviya** [comment]
you should try rebase-ing from `master`; #196 got merged so it should fix the ci issues you are having

**Comment by MineGame159** [comment]
Oh finally

**Review by cwfitzgerald — APPROVED** [review]

**Pull request merged**
