### PR TITLE
Expose missing native features up to v0.19.4

### PR DESCRIPTION
**Pull request by davnotdev**
#190 This exposes WGPU native features up to v0.19.4. However, I'm not sure what values should be attributed to each feature. From what I've observed, the "correct" ordering of features doesn't matter since they change with each WGPU version anyway.

### CODE REVIEW

**Review by rajveermalviya — CHANGES_REQUESTED** [review]
Thanks for working on this @davnotdev 

Unfortunately we can't expose some features directly because they also need to be coupled with API changes. So for this PR we can just remove such features for now, and make separate PRs for the ones that require API changes.

Here's a list I made for the features that can't exposed directly:

#### `TIMESTAMP_QUERY_INSIDE_PASSES`

Need to expose functions `RenderPassEncoder::write_timestamp` & `ComputePassEncoder::write_timestamp`.

#### `ADDRESS_MODE_CLAMP_TO_ZERO`

Need to expose struct member `SamplerDescriptor.border_color`.

#### `ADDRESS_MODE_CLAMP_TO_BORDER`

Need to expose enum `AddressMode::ClampToBorder`

#### `POLYGON_MODE_LINE` & `POLYGON_MODE_POINT`

Need to expose struct member `PrimitiveState.polygon_mode`.

#### `CONSERVATIVE_RASTERIZATION`

Need to expose struct member `PrimitiveState.conservative`.

#### `CLEAR_TEXTURE`

Need to expose function `CommandEncoder::clear_texture`.

#### `SPIRV_SHADER_PASSTHROUGH`

Need to expose function `Device::create_shader_module_spirv`

#### `MULTIVIEW`

Need to expose struct member `RenderPipelineDescriptor.multiview`

**Comment by davnotdev** [comment]
Sounds good! Thanks for listing them out too, that helps immensely.

**Review by almarklein — APPROVED** [review]

**Review by rajveermalviya — APPROVED** [review]

**Comment by rajveermalviya** [comment]
Thanks!

**Comment by melody-rs** [comment]
I'd like to contribute to the project by re-exposing some of these features- how would I do that?

**Pull request merged**
