### PR TITLE
Update headers

### PR DESCRIPTION
**Pull request by PJB3005**
Add wgpuAdapterGetInfo to replace wgpuAdapterRequestAdapterInfo. Actually implemented this time unlike wgpuAdapterRequestAdapterInfo. And wgpuAdapterInfoFreeMembers.

wgpuDeviceSetUncapturedErrorCallback replaced in favor of field on instance descriptor

wgpuSurfaceGetPreferredFormat deleted

Add usage to WGPUSurfaceCapabilities

### CODE REVIEW

**Comment by almarklein** [comment]
LGTM. Anyone know what the deal is with `WGPUAdapterProperties` vs `WGPUAdapterInfo`?

**Comment by PJB3005** [comment]
Seems like properties needs to be removed, actually: https://github.com/webgpu-native/webgpu-headers/issues/304#issuecomment-2161374820 https://github.com/webgpu-native/webgpu-headers/pull/305

**Comment by rajveermalviya** [comment]
CI is failing because `enumerate_adapters` example also needs to be updated:
https://github.com/gfx-rs/wgpu-native/actions/runs/9490406866/job/26153820533?pr=392

**Review by rajveermalviya — APPROVED** [review]

**Comment by rajveermalviya** [comment]
Thanks!

**Pull request merged**
